# Generated by Django 5.0.6 on 2024-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='/tag_images/default.png', upload_to='tag_images'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(),
        ),
    ]
