# Generated by Django 5.0.6 on 2024-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='updated_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
