# Generated by Django 5.0.6 on 2024-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartitems_updated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
