# Generated by Django 5.0.6 on 2024-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_myorders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
