# Generated by Django 5.0.6 on 2024-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_myorders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='payment_method',
            field=models.CharField(choices=[('cash-on-delivery', 'cash-on-delivery'), ('online-payment', 'online-payment')], default='cash-on-delivery', max_length=200),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
