# Generated by Django 5.0.6 on 2024-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_myorders_payment_method_alter_myorders_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='flavour_object',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='shape_object',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='tag_object',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='weight_object',
        ),
        migrations.AlterField(
            model_name='myorders',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
