# Generated by Django 5.0.6 on 2024-10-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cartitems_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart_object', 'cake_variant_object')},
        ),
    ]
